#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSendill
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbsendill")]
	public partial class DMModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DMModelDataContext() : 
				base(global::DMSendill.Properties.Settings.Default.dbsendillConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DMModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_car> tbl_cars
		{
			get
			{
				return this.GetTable<tbl_car>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cars")]
	public partial class tbl_car
	{
		
		private int _ID;
		
		private System.Nullable<short> _stationid;
		
		private string _carnumber;
		
		private string _code;
		
		private System.Nullable<bool> _listed;
		
		private string _carname;
		
		private System.Nullable<bool> _car1;
		
		private System.Nullable<bool> _car2;
		
		private System.Nullable<bool> _car3;
		
		private System.Nullable<bool> _car4;
		
		private System.Nullable<bool> _car5;
		
		private System.Nullable<bool> _car6;
		
		private System.Nullable<bool> _car7;
		
		private System.Nullable<bool> _car8;
		
		private System.Nullable<bool> _car9;
		
		private System.Nullable<bool> _car10;
		
		private System.Nullable<double> _length;
		
		private System.Nullable<double> _back_door_width;
		
		private System.Nullable<double> _back_door_height;
		
		private System.Nullable<double> _side_door_width;
		
		private System.Nullable<double> _side_door_height;
		
		private System.Nullable<double> _weight_limit;
		
		private System.Nullable<short> _lift_size;
		
		private System.Nullable<double> _Volume;
		
		private System.Nullable<double> _width;
		
		private string _model;
		
		private System.Nullable<double> _max_carry;
		
		private string _owner;
		
		private string _kt;
		
		private string _address;
		
		private string _town;
		
		private string _postcode;
		
		private string _phone;
		
		private string _mobile;
		
		private string _driver;
		
		private string _dkt;
		
		private string _daddress;
		
		private string _dtown;
		
		private string _dpostcode;
		
		private string _dphone;
		
		private string _dmobile;
		
		private System.Nullable<double> _heightofbox;
		
		public tbl_car()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationid", DbType="SmallInt")]
		public System.Nullable<short> stationid
		{
			get
			{
				return this._stationid;
			}
			set
			{
				if ((this._stationid != value))
				{
					this._stationid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carnumber", DbType="NVarChar(255)")]
		public string carnumber
		{
			get
			{
				return this._carnumber;
			}
			set
			{
				if ((this._carnumber != value))
				{
					this._carnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(255)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listed", DbType="Bit")]
		public System.Nullable<bool> listed
		{
			get
			{
				return this._listed;
			}
			set
			{
				if ((this._listed != value))
				{
					this._listed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carname", DbType="NVarChar(255)")]
		public string carname
		{
			get
			{
				return this._carname;
			}
			set
			{
				if ((this._carname != value))
				{
					this._carname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car1", DbType="Bit")]
		public System.Nullable<bool> car1
		{
			get
			{
				return this._car1;
			}
			set
			{
				if ((this._car1 != value))
				{
					this._car1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car2", DbType="Bit")]
		public System.Nullable<bool> car2
		{
			get
			{
				return this._car2;
			}
			set
			{
				if ((this._car2 != value))
				{
					this._car2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car3", DbType="Bit")]
		public System.Nullable<bool> car3
		{
			get
			{
				return this._car3;
			}
			set
			{
				if ((this._car3 != value))
				{
					this._car3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car4", DbType="Bit")]
		public System.Nullable<bool> car4
		{
			get
			{
				return this._car4;
			}
			set
			{
				if ((this._car4 != value))
				{
					this._car4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car5", DbType="Bit")]
		public System.Nullable<bool> car5
		{
			get
			{
				return this._car5;
			}
			set
			{
				if ((this._car5 != value))
				{
					this._car5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car6", DbType="Bit")]
		public System.Nullable<bool> car6
		{
			get
			{
				return this._car6;
			}
			set
			{
				if ((this._car6 != value))
				{
					this._car6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car7", DbType="Bit")]
		public System.Nullable<bool> car7
		{
			get
			{
				return this._car7;
			}
			set
			{
				if ((this._car7 != value))
				{
					this._car7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car8", DbType="Bit")]
		public System.Nullable<bool> car8
		{
			get
			{
				return this._car8;
			}
			set
			{
				if ((this._car8 != value))
				{
					this._car8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car9", DbType="Bit")]
		public System.Nullable<bool> car9
		{
			get
			{
				return this._car9;
			}
			set
			{
				if ((this._car9 != value))
				{
					this._car9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car10", DbType="Bit")]
		public System.Nullable<bool> car10
		{
			get
			{
				return this._car10;
			}
			set
			{
				if ((this._car10 != value))
				{
					this._car10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_length", DbType="Float")]
		public System.Nullable<double> length
		{
			get
			{
				return this._length;
			}
			set
			{
				if ((this._length != value))
				{
					this._length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_back_door_width", DbType="Float")]
		public System.Nullable<double> back_door_width
		{
			get
			{
				return this._back_door_width;
			}
			set
			{
				if ((this._back_door_width != value))
				{
					this._back_door_width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_back_door_height", DbType="Float")]
		public System.Nullable<double> back_door_height
		{
			get
			{
				return this._back_door_height;
			}
			set
			{
				if ((this._back_door_height != value))
				{
					this._back_door_height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_side_door_width", DbType="Float")]
		public System.Nullable<double> side_door_width
		{
			get
			{
				return this._side_door_width;
			}
			set
			{
				if ((this._side_door_width != value))
				{
					this._side_door_width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_side_door_height", DbType="Float")]
		public System.Nullable<double> side_door_height
		{
			get
			{
				return this._side_door_height;
			}
			set
			{
				if ((this._side_door_height != value))
				{
					this._side_door_height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight_limit", DbType="Float")]
		public System.Nullable<double> weight_limit
		{
			get
			{
				return this._weight_limit;
			}
			set
			{
				if ((this._weight_limit != value))
				{
					this._weight_limit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lift_size", DbType="SmallInt")]
		public System.Nullable<short> lift_size
		{
			get
			{
				return this._lift_size;
			}
			set
			{
				if ((this._lift_size != value))
				{
					this._lift_size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Float")]
		public System.Nullable<double> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this._Volume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width", DbType="Float")]
		public System.Nullable<double> width
		{
			get
			{
				return this._width;
			}
			set
			{
				if ((this._width != value))
				{
					this._width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(255)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this._model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_carry", DbType="Float")]
		public System.Nullable<double> max_carry
		{
			get
			{
				return this._max_carry;
			}
			set
			{
				if ((this._max_carry != value))
				{
					this._max_carry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner", DbType="NVarChar(255)")]
		public string owner
		{
			get
			{
				return this._owner;
			}
			set
			{
				if ((this._owner != value))
				{
					this._owner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kt", DbType="NVarChar(255)")]
		public string kt
		{
			get
			{
				return this._kt;
			}
			set
			{
				if ((this._kt != value))
				{
					this._kt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_town", DbType="NVarChar(255)")]
		public string town
		{
			get
			{
				return this._town;
			}
			set
			{
				if ((this._town != value))
				{
					this._town = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode", DbType="NVarChar(255)")]
		public string postcode
		{
			get
			{
				return this._postcode;
			}
			set
			{
				if ((this._postcode != value))
				{
					this._postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(255)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(255)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this._mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver", DbType="NVarChar(255)")]
		public string driver
		{
			get
			{
				return this._driver;
			}
			set
			{
				if ((this._driver != value))
				{
					this._driver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkt", DbType="NVarChar(255)")]
		public string dkt
		{
			get
			{
				return this._dkt;
			}
			set
			{
				if ((this._dkt != value))
				{
					this._dkt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daddress", DbType="NVarChar(255)")]
		public string daddress
		{
			get
			{
				return this._daddress;
			}
			set
			{
				if ((this._daddress != value))
				{
					this._daddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtown", DbType="NVarChar(255)")]
		public string dtown
		{
			get
			{
				return this._dtown;
			}
			set
			{
				if ((this._dtown != value))
				{
					this._dtown = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpostcode", DbType="NVarChar(255)")]
		public string dpostcode
		{
			get
			{
				return this._dpostcode;
			}
			set
			{
				if ((this._dpostcode != value))
				{
					this._dpostcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dphone", DbType="NVarChar(255)")]
		public string dphone
		{
			get
			{
				return this._dphone;
			}
			set
			{
				if ((this._dphone != value))
				{
					this._dphone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dmobile", DbType="NVarChar(255)")]
		public string dmobile
		{
			get
			{
				return this._dmobile;
			}
			set
			{
				if ((this._dmobile != value))
				{
					this._dmobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heightofbox", DbType="Float")]
		public System.Nullable<double> heightofbox
		{
			get
			{
				return this._heightofbox;
			}
			set
			{
				if ((this._heightofbox != value))
				{
					this._heightofbox = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
