//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendill_dataservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tours
    {
        public int ID { get; set; }
        public Nullable<short> id_customers { get; set; }
        public Nullable<short> id_cars { get; set; }
        public Nullable<int> id_owner { get; set; }
        public Nullable<System.DateTime> timedate { get; set; }
        public string customer { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public string phione { get; set; }
        public string note { get; set; }
    }
}
