//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendill_dataservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customers
    {
        public int ID { get; set; }
        public string custname { get; set; }
        public string kt { get; set; }
        public string address { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string vefur { get; set; }
        public string contact1 { get; set; }
        public string phone1 { get; set; }
        public string mobile1 { get; set; }
        public string contact2 { get; set; }
        public string phone2 { get; set; }
        public string mobile2 { get; set; }
    }
}
