//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendill_client.SendillServRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/sendillwcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vsk_types", Namespace="http://schemas.datacontract.org/2004/07/sendillwcf")]
    [System.SerializableAttribute()]
    public partial class vsk_types : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> calcnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> calcnum {
            get {
                return this.calcnumField;
            }
            set {
                if ((this.calcnumField.Equals(value) != true)) {
                    this.calcnumField = value;
                    this.RaisePropertyChanged("calcnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/sendillwcf")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> backdoorheightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> backdoorlengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> car9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string daddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dmobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dpostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string driverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> heightofboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isdelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> liftsizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> listedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> maxcarryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> sidedoorheightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> sidedoorlengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stationidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string townField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> volumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> weightlimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> widthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> backdoorheight {
            get {
                return this.backdoorheightField;
            }
            set {
                if ((this.backdoorheightField.Equals(value) != true)) {
                    this.backdoorheightField = value;
                    this.RaisePropertyChanged("backdoorheight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> backdoorlength {
            get {
                return this.backdoorlengthField;
            }
            set {
                if ((this.backdoorlengthField.Equals(value) != true)) {
                    this.backdoorlengthField = value;
                    this.RaisePropertyChanged("backdoorlength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car1 {
            get {
                return this.car1Field;
            }
            set {
                if ((this.car1Field.Equals(value) != true)) {
                    this.car1Field = value;
                    this.RaisePropertyChanged("car1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car10 {
            get {
                return this.car10Field;
            }
            set {
                if ((this.car10Field.Equals(value) != true)) {
                    this.car10Field = value;
                    this.RaisePropertyChanged("car10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car2 {
            get {
                return this.car2Field;
            }
            set {
                if ((this.car2Field.Equals(value) != true)) {
                    this.car2Field = value;
                    this.RaisePropertyChanged("car2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car3 {
            get {
                return this.car3Field;
            }
            set {
                if ((this.car3Field.Equals(value) != true)) {
                    this.car3Field = value;
                    this.RaisePropertyChanged("car3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car4 {
            get {
                return this.car4Field;
            }
            set {
                if ((this.car4Field.Equals(value) != true)) {
                    this.car4Field = value;
                    this.RaisePropertyChanged("car4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car5 {
            get {
                return this.car5Field;
            }
            set {
                if ((this.car5Field.Equals(value) != true)) {
                    this.car5Field = value;
                    this.RaisePropertyChanged("car5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car6 {
            get {
                return this.car6Field;
            }
            set {
                if ((this.car6Field.Equals(value) != true)) {
                    this.car6Field = value;
                    this.RaisePropertyChanged("car6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car7 {
            get {
                return this.car7Field;
            }
            set {
                if ((this.car7Field.Equals(value) != true)) {
                    this.car7Field = value;
                    this.RaisePropertyChanged("car7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car8 {
            get {
                return this.car8Field;
            }
            set {
                if ((this.car8Field.Equals(value) != true)) {
                    this.car8Field = value;
                    this.RaisePropertyChanged("car8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> car9 {
            get {
                return this.car9Field;
            }
            set {
                if ((this.car9Field.Equals(value) != true)) {
                    this.car9Field = value;
                    this.RaisePropertyChanged("car9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carname {
            get {
                return this.carnameField;
            }
            set {
                if ((object.ReferenceEquals(this.carnameField, value) != true)) {
                    this.carnameField = value;
                    this.RaisePropertyChanged("carname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carnumber {
            get {
                return this.carnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.carnumberField, value) != true)) {
                    this.carnumberField = value;
                    this.RaisePropertyChanged("carnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string daddress {
            get {
                return this.daddressField;
            }
            set {
                if ((object.ReferenceEquals(this.daddressField, value) != true)) {
                    this.daddressField = value;
                    this.RaisePropertyChanged("daddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dkt {
            get {
                return this.dktField;
            }
            set {
                if ((object.ReferenceEquals(this.dktField, value) != true)) {
                    this.dktField = value;
                    this.RaisePropertyChanged("dkt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dmobile {
            get {
                return this.dmobileField;
            }
            set {
                if ((object.ReferenceEquals(this.dmobileField, value) != true)) {
                    this.dmobileField = value;
                    this.RaisePropertyChanged("dmobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dphone {
            get {
                return this.dphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.dphoneField, value) != true)) {
                    this.dphoneField = value;
                    this.RaisePropertyChanged("dphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dpostcode {
            get {
                return this.dpostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.dpostcodeField, value) != true)) {
                    this.dpostcodeField = value;
                    this.RaisePropertyChanged("dpostcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string driver {
            get {
                return this.driverField;
            }
            set {
                if ((object.ReferenceEquals(this.driverField, value) != true)) {
                    this.driverField = value;
                    this.RaisePropertyChanged("driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtown {
            get {
                return this.dtownField;
            }
            set {
                if ((object.ReferenceEquals(this.dtownField, value) != true)) {
                    this.dtownField = value;
                    this.RaisePropertyChanged("dtown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> heightofbox {
            get {
                return this.heightofboxField;
            }
            set {
                if ((this.heightofboxField.Equals(value) != true)) {
                    this.heightofboxField = value;
                    this.RaisePropertyChanged("heightofbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isdel {
            get {
                return this.isdelField;
            }
            set {
                if ((this.isdelField.Equals(value) != true)) {
                    this.isdelField = value;
                    this.RaisePropertyChanged("isdel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kt {
            get {
                return this.ktField;
            }
            set {
                if ((object.ReferenceEquals(this.ktField, value) != true)) {
                    this.ktField = value;
                    this.RaisePropertyChanged("kt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> length {
            get {
                return this.lengthField;
            }
            set {
                if ((this.lengthField.Equals(value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> liftsize {
            get {
                return this.liftsizeField;
            }
            set {
                if ((this.liftsizeField.Equals(value) != true)) {
                    this.liftsizeField = value;
                    this.RaisePropertyChanged("liftsize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> listed {
            get {
                return this.listedField;
            }
            set {
                if ((this.listedField.Equals(value) != true)) {
                    this.listedField = value;
                    this.RaisePropertyChanged("listed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> maxcarry {
            get {
                return this.maxcarryField;
            }
            set {
                if ((this.maxcarryField.Equals(value) != true)) {
                    this.maxcarryField = value;
                    this.RaisePropertyChanged("maxcarry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerField, value) != true)) {
                    this.ownerField = value;
                    this.RaisePropertyChanged("owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postcodeField, value) != true)) {
                    this.postcodeField = value;
                    this.RaisePropertyChanged("postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> sidedoorheight {
            get {
                return this.sidedoorheightField;
            }
            set {
                if ((this.sidedoorheightField.Equals(value) != true)) {
                    this.sidedoorheightField = value;
                    this.RaisePropertyChanged("sidedoorheight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> sidedoorlength {
            get {
                return this.sidedoorlengthField;
            }
            set {
                if ((this.sidedoorlengthField.Equals(value) != true)) {
                    this.sidedoorlengthField = value;
                    this.RaisePropertyChanged("sidedoorlength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                if ((this.sizeField.Equals(value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stationid {
            get {
                return this.stationidField;
            }
            set {
                if ((this.stationidField.Equals(value) != true)) {
                    this.stationidField = value;
                    this.RaisePropertyChanged("stationid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string town {
            get {
                return this.townField;
            }
            set {
                if ((object.ReferenceEquals(this.townField, value) != true)) {
                    this.townField = value;
                    this.RaisePropertyChanged("town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> volume {
            get {
                return this.volumeField;
            }
            set {
                if ((this.volumeField.Equals(value) != true)) {
                    this.volumeField = value;
                    this.RaisePropertyChanged("volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> weightlimit {
            get {
                return this.weightlimitField;
            }
            set {
                if ((this.weightlimitField.Equals(value) != true)) {
                    this.weightlimitField = value;
                    this.RaisePropertyChanged("weightlimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="carbasic", Namespace="http://schemas.datacontract.org/2004/07/sendillwcf")]
    [System.SerializableAttribute()]
    public partial class carbasic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string driverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isdelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stationidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carname {
            get {
                return this.carnameField;
            }
            set {
                if ((object.ReferenceEquals(this.carnameField, value) != true)) {
                    this.carnameField = value;
                    this.RaisePropertyChanged("carname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carnumber {
            get {
                return this.carnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.carnumberField, value) != true)) {
                    this.carnumberField = value;
                    this.RaisePropertyChanged("carnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string driver {
            get {
                return this.driverField;
            }
            set {
                if ((object.ReferenceEquals(this.driverField, value) != true)) {
                    this.driverField = value;
                    this.RaisePropertyChanged("driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isdel {
            get {
                return this.isdelField;
            }
            set {
                if ((this.isdelField.Equals(value) != true)) {
                    this.isdelField = value;
                    this.RaisePropertyChanged("isdel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerField, value) != true)) {
                    this.ownerField = value;
                    this.RaisePropertyChanged("owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                if ((this.sizeField.Equals(value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stationid {
            get {
                return this.stationidField;
            }
            set {
                if ((this.stationidField.Equals(value) != true)) {
                    this.stationidField = value;
                    this.RaisePropertyChanged("stationid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendillServRef.ISendillService")]
    public interface ISendillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendillService/GetData", ReplyAction="http://tempuri.org/ISendillService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendillService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISendillService/GetDataUsingDataContractResponse")]
        sendill_client.SendillServRef.CompositeType GetDataUsingDataContract(sendill_client.SendillServRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendillService/GetAllVskTypes", ReplyAction="http://tempuri.org/ISendillService/GetAllVskTypesResponse")]
        sendill_client.SendillServRef.vsk_types[] GetAllVskTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendillService/GetAllCars", ReplyAction="http://tempuri.org/ISendillService/GetAllCarsResponse")]
        sendill_client.SendillServRef.Car[] GetAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendillService/GetBasicCarList", ReplyAction="http://tempuri.org/ISendillService/GetBasicCarListResponse")]
        sendill_client.SendillServRef.carbasic[] GetBasicCarList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendillServiceChannel : sendill_client.SendillServRef.ISendillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendillServiceClient : System.ServiceModel.ClientBase<sendill_client.SendillServRef.ISendillService>, sendill_client.SendillServRef.ISendillService {
        
        public SendillServiceClient() {
        }
        
        public SendillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public sendill_client.SendillServRef.CompositeType GetDataUsingDataContract(sendill_client.SendillServRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public sendill_client.SendillServRef.vsk_types[] GetAllVskTypes() {
            return base.Channel.GetAllVskTypes();
        }
        
        public sendill_client.SendillServRef.Car[] GetAllCars() {
            return base.Channel.GetAllCars();
        }
        
        public sendill_client.SendillServRef.carbasic[] GetBasicCarList() {
            return base.Channel.GetBasicCarList();
        }
    }
}
