//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
using SQLite;
using System;

namespace sendill_client
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<BÍLAR>();
                db.CreateTable<tbl_cars>();
                db.CreateTable<tbl_customers>();
                db.CreateTable<tbl_driver_customers>();
                db.CreateTable<tbl_driver_ledger_rec>();
                db.CreateTable<tbl_driver_ledger_record_type>();
                db.CreateTable<tbl_driver_ledgers>();
                db.CreateTable<tbl_driver_users>();
                db.CreateTable<tbl_ledger_entry_types>();
                db.CreateTable<tbl_pinnames>();
                db.CreateTable<tbl_pins>();
                db.CreateTable<tbl_tours>();
                db.CreateTable<tbl_vsk_periods>();
                db.CreateTable<tbl_vsk_types>();
                db.CreateTable<tblNewCar>();
            }
        }
    }
    
    public partial class BÍLAR
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        public Double A_Hurda_breidd { get; set; }
        public Double A_Hurda_haed { get; set; }
        [MaxLength(255)]
        public String Bilnumer { get; set; }
        public Double Breidd { get; set; }
        public Double Burdargeta { get; set; }
        [MaxLength(255)]
        public String Dregur_startar { get; set; }
        public Double Fjoldi { get; set; }
        [MaxLength(255)]
        public String Flytur_lengst { get; set; }
        [MaxLength(255)]
        public String Heimili_bilstjora { get; set; }
        [MaxLength(255)]
        public String Heimili_eiganda { get; set; }
        [MaxLength(255)]
        public String H_simi_bilstjora { get; set; }
        public Double Hurda_breidd { get; set; }
        public Double Hurda_haed { get; set; }
        [MaxLength(255)]
        public String H_simi_bilstjora2 { get; set; }
        [MaxLength(255)]
        public String H_simi_eiganda { get; set; }
        [MaxLength(255)]
        public String H_simi_eiganda2 { get; set; }
        public Double Kassahæð { get; set; }
        [MaxLength(255)]
        public String Koda_flokkar { get; set; }
        [MaxLength(255)]
        public String Kt_Bilstjora { get; set; }
        [MaxLength(255)]
        public String Kt_eiganda { get; set; }
        public Double Lengd { get; set; }
        [MaxLength(255)]
        public String Lyfta { get; set; }
        public Double Lyfta_staerd { get; set; }
        [MaxLength(255)]
        public String Nafn_bilstjora { get; set; }
        [MaxLength(255)]
        public String Nafn_eiganda { get; set; }
        public Double Nr { get; set; }
        [MaxLength(255)]
        public String Postnr_bilstjora { get; set; }
        public Double Postnr_eiganda { get; set; }
        public Double Rummal { get; set; }
        [MaxLength(255)]
        public String Simi_i_bil { get; set; }
        [MaxLength(255)]
        public String Skilaboð { get; set; }
        public DateTime Skilaboð_dags { get; set; }
        public DateTime Skilaboð_timi { get; set; }
        [MaxLength(255)]
        public String Skuldar { get; set; }
        [MaxLength(255)]
        public String Stadur_bilstjora { get; set; }
        [MaxLength(255)]
        public String Stadur_eiganda { get; set; }
        public Double Stardar_Flokkur { get; set; }
        [MaxLength(255)]
        public String Óskoðaður { get; set; }
        [MaxLength(255)]
        public String Tegurnd { get; set; }
        public Double Vinnu_field { get; set; }
    }
    public partial class tbl_cars
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        public Int16 stationid { get; set; }
        [MaxLength(255)]
        public String carnumber { get; set; }
        [MaxLength(255)]
        public String code { get; set; }
        public Boolean listed { get; set; }
        [MaxLength(255)]
        public String carname { get; set; }
        public Boolean car1 { get; set; }
        public Boolean car2 { get; set; }
        public Boolean car3 { get; set; }
        public Boolean car4 { get; set; }
        public Boolean car5 { get; set; }
        public Boolean car6 { get; set; }
        public Boolean car7 { get; set; }
        public Boolean car8 { get; set; }
        public Boolean car9 { get; set; }
        public Boolean car10 { get; set; }
        public Double length { get; set; }
        public Double back_door_width { get; set; }
        public Double back_door_height { get; set; }
        public Double side_door_width { get; set; }
        public Double side_door_height { get; set; }
        public Double weight_limit { get; set; }
        public Int16 lift_size { get; set; }
        public Double Volume { get; set; }
        public Double width { get; set; }
        [MaxLength(255)]
        public String model { get; set; }
        public Double max_carry { get; set; }
        [MaxLength(255)]
        public String owner { get; set; }
        [MaxLength(255)]
        public String kt { get; set; }
        [MaxLength(255)]
        public String address { get; set; }
        [MaxLength(255)]
        public String town { get; set; }
        [MaxLength(255)]
        public String postcode { get; set; }
        [MaxLength(255)]
        public String phone { get; set; }
        [MaxLength(255)]
        public String mobile { get; set; }
        [MaxLength(255)]
        public String driver { get; set; }
        [MaxLength(255)]
        public String dkt { get; set; }
        [MaxLength(255)]
        public String daddress { get; set; }
        [MaxLength(255)]
        public String dtown { get; set; }
        [MaxLength(255)]
        public String dpostcode { get; set; }
        [MaxLength(255)]
        public String dphone { get; set; }
        [MaxLength(255)]
        public String dmobile { get; set; }
        public Double heightofbox { get; set; }
        public Int16 size { get; set; }
    }
    public partial class tbl_customers
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        [MaxLength(100)]
        public String custname { get; set; }
        [MaxLength(255)]
        public String kt { get; set; }
        [MaxLength(100)]
        public String address { get; set; }
        [MaxLength(100)]
        public String town { get; set; }
        [MaxLength(20)]
        public String postcode { get; set; }
        [MaxLength(20)]
        public String phone { get; set; }
        [MaxLength(255)]
        public String fax { get; set; }
        [MaxLength(255)]
        public String email { get; set; }
        [MaxLength(255)]
        public String vefur { get; set; }
        [MaxLength(100)]
        public String contact1 { get; set; }
        [MaxLength(20)]
        public String phone1 { get; set; }
        [MaxLength(20)]
        public String mobile1 { get; set; }
        [MaxLength(100)]
        public String contact2 { get; set; }
        [MaxLength(20)]
        public String phone2 { get; set; }
        [MaxLength(20)]
        public String mobile2 { get; set; }
    }
    public partial class tbl_driver_customers
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        [MaxLength(50)]
        public String name { get; set; }
        [MaxLength(50)]
        public String address { get; set; }
        [MaxLength(5)]
        public String postgode { get; set; }
        [MaxLength(50)]
        public String address1 { get; set; }
        [MaxLength(11)]
        public String phone { get; set; }
        [MaxLength(11)]
        public String mobile { get; set; }
        [MaxLength(50)]
        public String email { get; set; }
        [MaxLength(15)]
        public String login { get; set; }
        [MaxLength(15)]
        public String password { get; set; }
        [Indexed(Name = "IX_FK_tbl_carstbl_driver_customers_tbl_driver_customers", Order = 0)]
        [NotNull]
        public Int32 tbl_carsID { get; set; }
    }
    public partial class tbl_driver_ledger_rec
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        public DateTime ldate { get; set; }
        public Int32 id_customer { get; set; }
        public Int32 id_ledger { get; set; }
        public Int32 id_period { get; set; }
        public Int32 id_record_type { get; set; }
    }
    public partial class tbl_driver_ledger_record_type
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        [MaxLength(15)]
        public String code { get; set; }
        public Boolean debit { get; set; }
        [MaxLength(100)]
        public String description { get; set; }
    }
    public partial class tbl_driver_ledgers
    {
        [PrimaryKey]
        public Int64 id { get; set; }
        [NotNull]
        public DateTime datefrom { get; set; }
        [NotNull]
        public DateTime dateto { get; set; }
        [MaxLength(15)]
        [NotNull]
        public String name { get; set; }
        public Double income { get; set; }
        public Double cost { get; set; }
        public Double vsk { get; set; }
        [MaxLength(50)]
        public String note { get; set; }
        [Indexed(Name = "IX_FK_tbl_cars_tbl_driver_ledgers_tbl_driver_ledgers", Order = 0)]
        [NotNull]
        public Int32 owner_id { get; set; }
        [NotNull]
        public Int32 period_id { get; set; }
        [NotNull]
        public Boolean is_open { get; set; }
    }
    public partial class tbl_driver_users
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        [MaxLength(50)]
        public String name { get; set; }
        [MaxLength(10)]
        public String login { get; set; }
        [MaxLength(10)]
        public String password { get; set; }
        [MaxLength(15)]
        public String code { get; set; }
        public Boolean isdelete { get; set; }
        public Int32 contact_id { get; set; }
    }
    public partial class tbl_ledger_entry_types
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        [MaxLength(10)]
        public String code { get; set; }
        [MaxLength(50)]
        public String description { get; set; }
    }
    public partial class tbl_pinnames
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        [MaxLength(100)]
        public String names { get; set; }
        public Int16 rows { get; set; }
    }
    public partial class tbl_pins
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        public Int16 idpin { get; set; }
        public Int32 idcar { get; set; }
        public Boolean foodbreak { get; set; }
        [MaxLength(10)]
        public String carcode { get; set; }
        public Int16 line { get; set; }
    }
    public partial class tbl_tours
    {
        [PrimaryKey]
        public Int64 ID { get; set; }
        public Int16 id_customers { get; set; }
        public Int16 id_cars { get; set; }
        public Int32 id_owner { get; set; }
        public DateTime timedate { get; set; }
        [MaxLength(255)]
        public String customer { get; set; }
        [MaxLength(255)]
        public String address { get; set; }
        [MaxLength(255)]
        public String contact { get; set; }
        [MaxLength(255)]
        public String phione { get; set; }
        [MaxLength(255)]
        public String note { get; set; }
    }
    public partial class tbl_vsk_periods
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        [MaxLength(10)]
        public String code { get; set; }
        [MaxLength(10)]
        public String date_from { get; set; }
        [MaxLength(10)]
        public String date_to { get; set; }
        [MaxLength(10)]
        public String description { get; set; }
    }
    public partial class tbl_vsk_types
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        [MaxLength(10)]
        public String code { get; set; }
        public Double calcnum { get; set; }
        [MaxLength(50)]
        public String description { get; set; }
    }
    public partial class tblNewCar
    {
        public Int16 stationid { get; set; }
        [MaxLength(255)]
        public String carnumber { get; set; }
        [MaxLength(255)]
        public String code { get; set; }
        public Int16 listed { get; set; }
        [MaxLength(255)]
        public String carname { get; set; }
        public Boolean car1 { get; set; }
        public Boolean car2 { get; set; }
        public Boolean car3 { get; set; }
        public Boolean car4 { get; set; }
        public Boolean car5 { get; set; }
        public Boolean car6 { get; set; }
        public Boolean car7 { get; set; }
        public Boolean car8 { get; set; }
        public Boolean car9 { get; set; }
        public Boolean car10 { get; set; }
        public Double length { get; set; }
        public Double back_door_width { get; set; }
        public Double back_door_height { get; set; }
        public Double side_door_width { get; set; }
        public Double side_door_height { get; set; }
        public Double weight_limit { get; set; }
        public Int16 lift_size { get; set; }
        public Double Volume { get; set; }
        public Double width { get; set; }
        [MaxLength(255)]
        public String model { get; set; }
        public Double max_carry { get; set; }
        [MaxLength(255)]
        public String owner { get; set; }
        [MaxLength(255)]
        public String kt { get; set; }
        [MaxLength(255)]
        public String address { get; set; }
        [MaxLength(255)]
        public String town { get; set; }
        [MaxLength(255)]
        public String postcode { get; set; }
        [MaxLength(255)]
        public String phone { get; set; }
        [MaxLength(255)]
        public String mobile { get; set; }
        [MaxLength(255)]
        public String driver { get; set; }
        [MaxLength(255)]
        public String dkt { get; set; }
        [MaxLength(255)]
        public String daddress { get; set; }
        [MaxLength(255)]
        public String dtown { get; set; }
        [MaxLength(255)]
        public String dpostcode { get; set; }
        [MaxLength(255)]
        public String dphone { get; set; }
        [MaxLength(255)]
        public String dmobile { get; set; }
        public Double heightofbox { get; set; }
        [NotNull]
        public Int32 size { get; set; }
    }
}
