//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendill_client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbsendillEntities : DbContext
    {
        public dbsendillEntities()
            : base("name=dbsendillEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_cars> tbl_cars { get; set; }
        public DbSet<BÍLAR> BÍLAR { get; set; }
        public DbSet<tbl_customers> tbl_customers { get; set; }
        public DbSet<tbl_driver_customers> tbl_driver_customers { get; set; }
        public DbSet<tbl_driver_ledger_rec> tbl_driver_ledger_rec { get; set; }
        public DbSet<tbl_driver_ledger_record_type> tbl_driver_ledger_record_type { get; set; }
        public DbSet<tbl_driver_ledgers> tbl_driver_ledgers { get; set; }
        public DbSet<tbl_driver_users> tbl_driver_users { get; set; }
        public DbSet<tbl_ledger_entry_types> tbl_ledger_entry_types { get; set; }
        public DbSet<tbl_pinnames> tbl_pinnames { get; set; }
        public DbSet<tbl_pins> tbl_pins { get; set; }
        public DbSet<tbl_tours> tbl_tours { get; set; }
        public DbSet<tbl_vsk_periods> tbl_vsk_periods { get; set; }
        public DbSet<tbl_vsk_types> tbl_vsk_types { get; set; }
        public DbSet<tblNewCar> tblNewCars { get; set; }
    }
}
