//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendill_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEntity
    {
        public int ID { get; set; }
        public Nullable<int> stationid { get; set; }
        public string carnumber { get; set; }
        public string code { get; set; }
        public Nullable<bool> listed { get; set; }
        public string carname { get; set; }
        public Nullable<bool> car1 { get; set; }
        public Nullable<bool> car2 { get; set; }
        public Nullable<bool> car3 { get; set; }
        public Nullable<bool> car4 { get; set; }
        public Nullable<bool> car5 { get; set; }
        public Nullable<bool> car6 { get; set; }
        public Nullable<bool> car7 { get; set; }
        public Nullable<bool> car8 { get; set; }
        public Nullable<bool> car9 { get; set; }
        public Nullable<bool> car10 { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> back_door_width { get; set; }
        public Nullable<double> back_door_height { get; set; }
        public Nullable<double> side_door_width { get; set; }
        public Nullable<double> side_door_height { get; set; }
        public Nullable<double> weight_limit { get; set; }
        public Nullable<short> lift_size { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> width { get; set; }
        public string model { get; set; }
        public Nullable<double> max_carry { get; set; }
        public string owner { get; set; }
        public string kt { get; set; }
        public string address { get; set; }
        public string town { get; set; }
        public string postcode { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string driver { get; set; }
        public string dkt { get; set; }
        public string daddress { get; set; }
        public string dtown { get; set; }
        public string dpostcode { get; set; }
        public string dphone { get; set; }
        public string dmobile { get; set; }
        public Nullable<double> heightofbox { get; set; }
        public Nullable<double> size { get; set; }
    }
}
