//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendill_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntity
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> logtimestamp { get; set; }
        public string logtext { get; set; }
    }
}
